version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123abc
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - common-net
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     ENV_NAME: prod
  #   ports:
  #     - 8080:8080
  #   links:
  #     - db
  #   volumes:
  #     - ./:/src
  #   restart: always
  #   networks:
  #     - common-net
networks:
  common-net: {}
volumes:
  db:
    driver: local